/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package codigo;

import java.awt.Color;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.Image;
import java.awt.image.BufferedImage;
import java.io.IOException;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.HashMap;
import javax.imageio.ImageIO;
import javax.sound.sampled.AudioSystem;
import javax.sound.sampled.Clip;
import javax.sound.sampled.LineUnavailableException;
import javax.sound.sampled.UnsupportedAudioFileException;

/**
 *
 * @author ruben
 */
public class VentanaPokedex extends javax.swing.JFrame {

    BufferedImage buffer1 = null;
    Image imagen1 = null;
    int contador = 0;
    Clip audio;

    Statement estado;
    ResultSet resultadoConsulta;
    Connection conexion;

    //estructura para guardar todo el contenido de la base de datos de golpe
    HashMap<String, Pokemon> listaPokemons = new HashMap();

    @Override
    public void paint(Graphics g) {
        super.paintComponents(g);
        Graphics2D g2 = (Graphics2D) imagenPokemon.getGraphics();
        g2.drawImage(buffer1, 0, 0, imagenPokemon.getWidth(), imagenPokemon.getHeight(), null);
    }

    /**
     * Creates new form VentanaPokedex
     */
    public VentanaPokedex() {
        initComponents();
        try {
            imagen1 = ImageIO.read((getClass().getResource("/imagenes/black-white.png")));
        } catch (IOException ex) {

        }
        buffer1 = (BufferedImage) imagenPokemon.createImage(imagenPokemon.getWidth(), imagenPokemon.getHeight());
        Graphics2D g2 = buffer1.createGraphics();

        dibujaElPokemonQueEstaEnLaPosicion(30);

        try {
            Class.forName("com.mysql.jdbc.Driver");
            conexion = DriverManager.getConnection("jdbc:mysql://127.0.0.1/pokedex", "root", "");
            estado = conexion.createStatement();
            resultadoConsulta = estado.executeQuery("Select * from pokemon");
            //recorremos el array del resultado 1a1 para ir cargandolo en el hashmap

            while (resultadoConsulta.next()) {
                Pokemon p = new Pokemon();
                p.nombre = resultadoConsulta.getString("nombre");
                p.especie = resultadoConsulta.getString("especie");
                p.tipo1 = resultadoConsulta.getString("tipo1");
                p.tipo2 = resultadoConsulta.getString("tipo2");
                p.peso = resultadoConsulta.getString("peso");
                p.altura = resultadoConsulta.getString("altura");
                p.preEvolucion = resultadoConsulta.getInt("preEvolucion");
                p.posEvolucion = resultadoConsulta.getInt("posEvolucion");
                //añado el pokemon recien creado al Hashmap
                listaPokemons.put(resultadoConsulta.getString("id"), p);

            }
        } catch (Exception e) {
            System.out.println(e.getMessage());
            System.out.println("hay un error");
        }

    }

    private void dibujaElPokemonQueEstaEnLaPosicion(int posicion) {
        int fila = posicion / 31;
        int columna = posicion % 31;
        Graphics2D g2 = (Graphics2D) buffer1.getGraphics();
        g2.setColor(Color.black);
        g2.fillRect(0, 0, imagenPokemon.getWidth(), imagenPokemon.getHeight());
        g2.drawImage(imagen1, 0, 0, imagenPokemon.getWidth(), imagenPokemon.getHeight(), columna * 96, fila * 96, columna * 96 + 96, fila * 96 + 96, null);
        repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        imagenPokemon = new javax.swing.JPanel();
        izq = new javax.swing.JButton();
        der = new javax.swing.JButton();
        nombrePokemon = new javax.swing.JLabel();
        tipo1 = new javax.swing.JLabel();
        peso = new javax.swing.JLabel();
        altura = new javax.swing.JLabel();
        tipo2 = new javax.swing.JLabel();
        Altura = new javax.swing.JLabel();
        Peso = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        javax.swing.GroupLayout imagenPokemonLayout = new javax.swing.GroupLayout(imagenPokemon);
        imagenPokemon.setLayout(imagenPokemonLayout);
        imagenPokemonLayout.setHorizontalGroup(
            imagenPokemonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 240, Short.MAX_VALUE)
        );
        imagenPokemonLayout.setVerticalGroup(
            imagenPokemonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 130, Short.MAX_VALUE)
        );

        getContentPane().add(imagenPokemon, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 350, 240, 130));

        izq.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/izquierda.png"))); // NOI18N
        izq.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                izqActionPerformed(evt);
            }
        });
        getContentPane().add(izq, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 540, 40, -1));

        der.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/derecha.png"))); // NOI18N
        der.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                derActionPerformed(evt);
            }
        });
        getContentPane().add(der, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 540, 40, -1));

        nombrePokemon.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        nombrePokemon.setForeground(new java.awt.Color(255, 0, 0));
        getContentPane().add(nombrePokemon, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 560, 110, 30));

        tipo1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        tipo1.setForeground(new java.awt.Color(255, 0, 0));
        getContentPane().add(tipo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(416, 440, 240, 40));

        peso.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        peso.setForeground(new java.awt.Color(255, 51, 51));
        getContentPane().add(peso, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 550, 100, 30));

        altura.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        altura.setForeground(new java.awt.Color(255, 0, 0));
        getContentPane().add(altura, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 550, 100, 30));

        tipo2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        tipo2.setForeground(new java.awt.Color(255, 0, 0));
        getContentPane().add(tipo2, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 380, 235, 40));

        Altura.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Altura.setText("Altura");
        getContentPane().add(Altura, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 500, 70, 30));

        Peso.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Peso.setText("peso");
        getContentPane().add(Peso, new org.netbeans.lib.awtextra.AbsoluteConstraints(423, 500, 60, 20));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/pokedex.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 1010, 760));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void izqActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_izqActionPerformed
        dibujaElPokemonQueEstaEnLaPosicion(contador);
Pokemon p = listaPokemons.get(String.valueOf(contador + 1));
  try {
            audio = AudioSystem.getClip();
            audio.open(AudioSystem.getAudioInputStream(getClass().getResource("/sonidos/button5.wav")));
            audio.start();
        } catch (LineUnavailableException ex) {
            
        } catch (UnsupportedAudioFileException ex) {
               
        } catch (IOException ex) {
         
        }
        if (p != null) {
            nombrePokemon.setText(p.nombre);
            tipo1.setText(p.tipo1);
            tipo2.setText(p.tipo2);
            peso.setText(p.peso);
            altura.setText(p.altura);
        } else {
            nombrePokemon.setText("no hay datos");
            tipo1.setText("no hay datos");
            tipo2.setText("no hay datos");
            peso.setText("no hay datos");
            altura.setText("no hay datos");
        }
        contador--;
        if (contador <= 0) {
            contador = 0;
        }
    }//GEN-LAST:event_izqActionPerformed

    private void derActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_derActionPerformed

        contador++;
        if (contador >= 649) {
            contador = 649;
        }
        dibujaElPokemonQueEstaEnLaPosicion(contador);
        Pokemon p = listaPokemons.get(String.valueOf(contador + 1));
         try {
            audio = AudioSystem.getClip();
            audio.open(AudioSystem.getAudioInputStream(getClass().getResource("/sonidos/button5.wav")));
            audio.start();
        } catch (LineUnavailableException ex) {
            
        } catch (UnsupportedAudioFileException ex) {
               
        } catch (IOException ex) {
         
        }
        if (p != null) {
            nombrePokemon.setText(p.nombre);
            tipo1.setText(p.tipo1);
            tipo2.setText(p.tipo2);
            peso.setText(p.peso);
            altura.setText(p.altura);
        } else {
            nombrePokemon.setText("no hay datos");
            tipo1.setText("no hay datos");
            tipo2.setText("no hay datos");
            peso.setText("no hay datos");
            altura.setText("no hay datos");
        }
    }//GEN-LAST:event_derActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaPokedex.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaPokedex.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaPokedex.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaPokedex.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaPokedex().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Altura;
    private javax.swing.JLabel Peso;
    private javax.swing.JLabel altura;
    private javax.swing.JButton der;
    private javax.swing.JPanel imagenPokemon;
    private javax.swing.JButton izq;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel nombrePokemon;
    private javax.swing.JLabel peso;
    private javax.swing.JLabel tipo1;
    private javax.swing.JLabel tipo2;
    // End of variables declaration//GEN-END:variables
}
